### ISSUE TITLE
O winston espera que exista apenas Line Feed (\n) no final do log, qualquer coisa diferente impede reinicio do server.js

### ISSUE THREAD

**Issue by marco-jardim** [RioBus/website#11]
Caso haja algum crash, interrupção voluntária ou abertura do .log em um editor de texto, ele pode não possuir mais no final o line feed. Quando isso ocorre o winston não consegue ser reiniciado no reinício do server.js.

Possível solução: antes de entregar o .log pro winston, incluir o \n como o último caracter do arquivo e salvar.

**Comment by fmsouza** [comment]
O servidor não faz mais parte deste repositório.
