### ISSUE TITLE
Mostrando ícone verde pra ônibus atualizado há 15 horas no Safari

### ISSUE THREAD

**Issue by macecchi** [RioBus/website#14]
Só consegui reproduzir esse problema pelo Safari no OS X. 

http://riob.us/?885

Quando visualizando pelo Chrome, os ônibus aparecem com o ícone vermelho. No Safari, todos aparecem verdes.

**Comment by marco-jardim** [comment]
Acho que isso acontece por causa do moment.js, ao formatar pro locale
padrão do usuário...
Em 23/07/2015 19:11, "Mario Cecchi" <notifications@github.com> escreveu:

**Comment by fmsouza** [comment]
Se me lembro bem, o site nem está usando a moment.js. A formatação é feita "na mão".

**Comment by marco-jardim** [comment]
Agora a formatação está via .toLocaleDateString(), dá uma testada aí de novo @macecchi !

**Comment by macecchi** [comment]
Não consigo testar agora por causa do issue #15 hahahaha. @fmsouza vc não tem Safari aí? contigo tá funcionando?

**Comment by macecchi** [comment]
O bug continua, parece que em qualquer navegador agora. Por exemplo, agora são 2:00 e o ônibus de 1:28 ainda está verde.
![screen shot 2016-02-06 at 02 04 10](https://cloud.githubusercontent.com/assets/5282467/12864557/130ade48-cc76-11e5-8109-84b934925043.png)

**Comment by macecchi** [comment]
Acho que agora foi corrigido de vez com o 6c7c59ac6491b010d819f8110e33ecfe68f9fe58.
