### ISSUE TITLE
Erro nas requests ao REST pelo Safari 8.0.7

### ISSUE THREAD

**Issue by macecchi** [RioBus/website#15]
As requests pro rest.riob.us estão sendo bloqueadas no Safari do OS X (não sei se é em todas as versões ou só nessa - Safari 8.0.7 no OS X 10.10.4).

    XMLHttpRequest cannot load http://rest.riob.us/v2/search/3/885. Request header field DNT is not allowed by Access-Control-Allow-Headers.

**Comment by macecchi** [comment]
Tive esse problema recentemente e é um protocolo (novo?) de segurança que bloqueia requisições pra outros domínios/subdomínios pelo browser (deve ser pra evitar ataques de cross-scripting, sei la).

Precisa adicionar esse header nas respostas do REST autorizando o domínio principal. Nesse formato:

    Access-Control-Allow-Headers riob.us

(não tenho ctz 100% mas acho q é isso e é fácil de testar)

**Comment by macecchi** [comment]
Só pra lembrar que isso continua acontecendo :(

**Comment by marco-jardim** [comment]
Acho que poderíamos migrar a página pra v3 do REST, e ver se o problema continua

**Comment by fmsouza** [comment]
Precisamos fazer uma atualização das boas na página, na verdade, né. Já poderíamos atualizar tanto a API de ônibus quanto a de itinerários para a v3.
